### ISSUE TITLE
Add support for specifying language

### ISSUE THREAD

**Issue by davsclaus** [funktionio/funktion-connectors#234]
for the steps such as filter, choice etc its hardcoded to jsonpath as the languge.

We should allow to define what language we want to use, so we can do simple, xpath and others as well

**Comment by davsclaus** [comment]
You can now specify the language
```
flows:
- steps:
  - kind: "endpoint"
    uri: "direct:start"
  - kind: "filter"
    expression: "${body} contains 'James'"
    language: "simple"
    steps:
    - kind: "endpoint"
      uri: "mock:matched"
  - kind: "endpoint"
    uri: "mock:allMessages"
```

The default language is still jsonpath
